kind: pipeline
type: ssh
name: default

clone:
  disable: true

server:
  host:
    from_secret: ssh_ip
  user: root
  password:
    from_secret: ssh_password

steps:
  - name: clone
    commands:
      - cd /root/hackbook
      - git pull gogs master
      - echo $JWT_SECRET >/tmp/a.txt
      - make
    environment:
      JWT_SECRET:
        from_secret: JWT_SECRET
      TYPEORM_HOST:
        from_secret: TYPEORM_HOST
      TYPEORM_PASSWORD:
        from_secret: TYPEORM_PASSWORD
      TYPEORM_USERNAME:
        from_secret: urie

trigger:
  branch:
    - master
  event:
    - push
