version: "3.5"

services:
  hackbook-front:
    build: ./front-end
    ports:
      - "7122:8080"
    container_name: "hackbook-front"
    networks:
      - default

  hackbook-back:
    build: ./back-end
    container_name: "hackbook-back"
    volumes:
      - /root/data/hackbook:/root/data
    environment:
      - PORT=8080
      - SSO=https://sso.sweetlove.top
      - JWT_SECRET=Fwet)9243?
      - DATA_DIR=/root/data
      - SSO_RETURN=https://book.sweetlove.top/api/login
    networks:
      - default