version: "3.5"

services:
  front:
    build: ./front-end
    ports:
      - "7122:80"
    container_name: "hackbook-front"

  back:
    build: ./back-end
    container_name: "hackbook-back"
    environment:
      - PORT=8080
      - SSO=https://sso.sweetlove.top
      - JWT_SECRET=Fwet)9243?
    networks:
      - mysql_default

networks:
  mysql_default:
    external: true