version: '3.5'

services:
  back:
    build: .
    container_name: 'hackbook-back'
    ports:
      - 10000:10000
    environment:
      - PORT=10000
      - SSO=https://sso.sweetlove.top
      - JWT_SECRET=${JWT_SECRET}
      - TYPEORM_HOST=${TYPEORM_HOST}
      - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
      - TYPEORM_USERNAME=${TYPEORM_USERNAME}
