version: "3.5"

services:
  back:
    build: .
    container_name: "hackbook-back"
    ports:
      - 10000:10000
    environment:
      - PORT=10000
      - SSO=https://sso.sweetlove.top
      - JWT_SECRET=Fwet)9243?
      - TYPEORM_HOST=mysql
      - TYPEORM_PASSWORD=youling
      - TYPEORM_USERNAME=root
    networks:
      - mysql_default
      - default

networks:
  mysql_default:
    external: true