GET http://localhost:4000/1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxIiwiaWF0IjoxNjExMjk0NDM4LCJleHAiOjE2MTU2MTQ0Mzh9.-_alArSrreGVXEtLzsWK48CcqbVwDZO3bOYx2Ddb08o
content-type: application/json
HOST: 1
